/**:
    ros__parameters:
        RATE: 20.0
        QUEUE_SIZE: 10
        MAX_TAKEOFF_SPEED: 1.0
        A: 0.1
        B: 1.5
        C: 50.0
        H_DES: 1.0
        K_H: 1.0
        EARTH_RADIUS: 6371000
        TARGET_ID: 200
        MAX_SWARMING_SPEED: 1.0
        TIMEOUT: 5
        UWB_ON: false
        SINGLE_DRONE_FOR_TEST: false

targetRover:
    targetRover:
        ros__parameters:
            MAX_THROTTLE: 1.0
            MAX_ROTATION: 0.785
            KT: 1.0
            KR: 1.0
            DISTANCE_ERROR: 0.3

trackingVelocityCalculator:
    trackingVelocityCalculator:
        ros__parameters:
            MAX_TRACKING_SPEED: 3.0
            K_P: 1.2
            K_I: 0.01
            K_D: 0.7
            FILTER_WINDOW: 1
            MAX_ERROR_FOR_INTEGRAL_AND_DERIVATIVE: 2.0

X500_0:
    X500_0:
        ros__parameters:
            ID: 0
            NOT_FLYING_FOR_TEST: false

X500_1:
    X500_1:
        ros__parameters:
            ID: 1
            NOT_FLYING_FOR_TEST: false

X500_2:
    X500_2:
        ros__parameters:
            ID: 2
            NOT_FLYING_FOR_TEST: false

X500_3:
    X500_3:
        ros__parameters:
            ID: 3
            NOT_FLYING_FOR_TEST: false

X500_4:
    X500_4:
        ros__parameters:
            ID: 4
            NOT_FLYING_FOR_TEST: false

X500_5:
    X500_5:
        ros__parameters:
            ID: 5
            NOT_FLYING_FOR_TEST: false
