# Control mode service to request functionalities from DroneController

string control_mode   # Requested control mode
float64 x             # Requested x position
float64 y             # Requested y position
float64 z             # Requested z position
---
string message        # Return message
